[project]
name = "audio-loudness-batch-normalize"
version = "0.1.0"
description = "only for testing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["librosa>=0.11.0", "matplotlib>=3.10.1"]
